import hre from "hardhat";

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying contracts with account:", deployer.address);
  console.log(
    "Account balance:",
    (await hre.ethers.provider.getBalance(deployer.address)).toString(),
  );

  const nonce = await deployer.getNonce("latest");

  // 1. Deploy the Groth16 Verifier
  console.log("\n📦 Deploying Groth16Verifier...");
  const Verifier = await hre.ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy({ nonce });
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log("✅ Groth16Verifier deployed to:", verifierAddress);

  // 2. Deploy FaceLockedTransfer
  console.log("\n📦 Deploying FaceLockedTransfer...");
  const FaceLockedTransfer = await hre.ethers.getContractFactory(
    "FaceLockedTransfer",
  );
  const faceLock = await FaceLockedTransfer.deploy(verifierAddress, {
    nonce: nonce + 1,
  });
  await faceLock.waitForDeployment();
  const faceLockAddress = await faceLock.getAddress();
  console.log("✅ FaceLockedTransfer deployed to:", faceLockAddress);

  // Summary
  console.log("\n" + "═".repeat(50));
  console.log("  DEPLOYMENT SUMMARY");
  console.log("═".repeat(50));
  console.log(`  Network:              ${hre.network.name}`);
  console.log(`  Deployer:             ${deployer.address}`);
  console.log(`  Groth16Verifier:      ${verifierAddress}`);
  console.log(`  FaceLockedTransfer:   ${faceLockAddress}`);
  console.log("═".repeat(50));
  console.log(
    "\n✅ Deployed verifier source is contracts/Groth16Verifier.sol (generated by snarkjs).\n",
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
