// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./Groth16Verifier.sol";

/**
 * @title FaceLockedTransfer
 * @notice Lock ETH to a face commitment. Only the person whose face matches
 *         the commitment can claim the funds by submitting a ZK proof.
 *
 * @dev Architecture:
 *   SENDER:    deposit(commitment) → locks ETH to poseidon_hash(face_embedding)
 *   RECIPIENT: claim(lockId, proof) → submits Groth16 proof that their face matches
 *
 *   The ZK circuit (generated by Bionetta) proves:
 *     1. The prover ran BioNetV1 on their selfie → embedding_B
 *     2. hash(embedding_A) == commitment (stored on-chain)
 *     3. distance²(embedding_A, embedding_B) ≤ threshold
 *   Without revealing either embedding or the original images.
 */
contract FaceLockedTransfer {
    // ─── State ──────────────────────────────────────────────────────

    Groth16Verifier public immutable verifier;

    struct Lock {
        address sender;
        uint256 amount;
        uint256 faceCommitment; // poseidon_hash(reference_embedding)
        uint256 threshold; // max allowed distance² (arithmetized)
        uint256 nonce; // replay protection
        bool claimed;
        uint256 createdAt;
    }

    mapping(uint256 => Lock) public locks;
    uint256 public nextLockId;

    // ─── Events ─────────────────────────────────────────────────────

    event FundsLocked(
        uint256 indexed lockId,
        address indexed sender,
        uint256 amount,
        uint256 faceCommitment,
        uint256 threshold
    );

    event FundsClaimed(
        uint256 indexed lockId,
        address indexed recipient,
        uint256 amount
    );

    event FundsRefunded(
        uint256 indexed lockId,
        address indexed sender,
        uint256 amount
    );

    // ─── Errors ─────────────────────────────────────────────────────

    error NoValueSent();
    error AlreadyClaimed();
    error InvalidProof();
    error CommitmentMismatch();
    error NotSender();
    error TooEarly();
    error ThresholdOutOfRange();

    // ─── Constants ──────────────────────────────────────────────────

    /// @notice Time after which the sender can reclaim their funds
    uint256 public constant REFUND_DELAY = 30 days;

    /// @notice Hard upper bound for lock threshold to reduce false-positive risk.
    uint256 public constant MAX_THRESHOLD = 100_000_000;

    // ─── Constructor ────────────────────────────────────────────────

    constructor(address _verifier) {
        verifier = Groth16Verifier(_verifier);
    }

    // ─── Deposit ────────────────────────────────────────────────────

    /**
     * @notice Lock ETH to a face commitment.
     * @param faceCommitment The poseidon hash of the recipient's face embedding.
     *        Generated client-side: poseidon_hash(BioNetV1.predict(recipient_photo))
     * @param threshold Maximum allowed distance² between embeddings.
     *        Higher = more lenient matching. Typical: ~327680 (0.01² at precision 15)
     * @param nonce Unique value to prevent proof replay across locks.
     */
    function deposit(
        uint256 faceCommitment,
        uint256 threshold,
        uint256 nonce
    ) external payable {
        if (msg.value == 0) revert NoValueSent();
        if (threshold == 0 || threshold > MAX_THRESHOLD)
            revert ThresholdOutOfRange();

        uint256 lockId = nextLockId++;

        locks[lockId] = Lock({
            sender: msg.sender,
            amount: msg.value,
            faceCommitment: faceCommitment,
            threshold: threshold,
            nonce: nonce,
            claimed: false,
            createdAt: block.timestamp
        });

        emit FundsLocked(
            lockId,
            msg.sender,
            msg.value,
            faceCommitment,
            threshold
        );
    }

    // ─── Claim ──────────────────────────────────────────────────────

    /**
     * @notice Claim locked funds by proving face match via ZK proof.
     * @dev The proof is generated client-side by Bionetta's ProverWorker.
     *      Public signals layout:
     *        [0] = address (msg.sender, bound in circuit)
     *        [1] = threshold²
     *        [2] = nonce
     *        [3] = faceCommitment
     * @param lockId The ID of the lock to claim.
     * @param _pA Groth16 proof element A
     * @param _pB Groth16 proof element B
     * @param _pC Groth16 proof element C
     * @param _pubSignals Public signals from the ZK circuit
     */
    function claim(
        uint256 lockId,
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals
    ) external {
        Lock storage lock = locks[lockId];

        if (lock.claimed) revert AlreadyClaimed();

        // Security Checks based on Bionetta outputs
        // _pubSignals[0] = featuresHash (Poseidon hash of target embedding)
        // _pubSignals[1] = isCompleted (1 if distance <= threshold, 0 otherwise)
        // _pubSignals[2] = address
        // _pubSignals[3] = threshold
        // _pubSignals[4] = nonce

        if (_pubSignals[0] != lock.faceCommitment) revert CommitmentMismatch();
        if (_pubSignals[1] != 1) revert InvalidProof();

        // Cryptographic Binding Checks
        if (_pubSignals[2] != uint256(uint160(msg.sender)))
            revert InvalidProof();
        if (_pubSignals[3] != lock.threshold) revert InvalidProof();
        if (_pubSignals[4] != lock.nonce) revert InvalidProof();

        // Verify the ZK proof on-chain
        if (!verifier.verifyProof(_pA, _pB, _pC, _pubSignals))
            revert InvalidProof();

        // Mark as claimed and transfer
        lock.claimed = true;

        (bool success, ) = payable(msg.sender).call{value: lock.amount}("");
        require(success, "Transfer failed");

        emit FundsClaimed(lockId, msg.sender, lock.amount);
    }

    // ─── Refund ─────────────────────────────────────────────────────

    /**
     * @notice Sender can reclaim funds after REFUND_DELAY if unclaimed.
     * @param lockId The ID of the lock to refund.
     */
    function refund(uint256 lockId) external {
        Lock storage lock = locks[lockId];

        if (lock.claimed) revert AlreadyClaimed();
        if (msg.sender != lock.sender) revert NotSender();
        if (block.timestamp < lock.createdAt + REFUND_DELAY) revert TooEarly();

        lock.claimed = true;

        (bool success, ) = payable(msg.sender).call{value: lock.amount}("");
        require(success, "Transfer failed");

        emit FundsRefunded(lockId, msg.sender, lock.amount);
    }

    // ─── View ───────────────────────────────────────────────────────

    /**
     * @notice Get lock details.
     */
    function getLock(
        uint256 lockId
    )
        external
        view
        returns (
            address sender,
            uint256 amount,
            uint256 faceCommitment,
            uint256 threshold,
            uint256 nonce,
            bool claimed,
            uint256 createdAt
        )
    {
        Lock storage lock = locks[lockId];
        return (
            lock.sender,
            lock.amount,
            lock.faceCommitment,
            lock.threshold,
            lock.nonce,
            lock.claimed,
            lock.createdAt
        );
    }
}
