"""
Package for verifying proofs generated by the proving backend.
"""

import subprocess
from logging import Logger
from pathlib import Path

from tf_bionetta.codegen.utils import get_system
from tf_bionetta.logging.pretty import Panel
from tf_bionetta.specs.backend_enums import Groth16, UltraGroth
from tf_bionetta.specs.engine import Engine
from tf_bionetta.logging.logger import create_logger, console
from tf_bionetta.logging.verbose import VerboseMode


SYSTEM_NAME = get_system()

class Verifier:
    """
    Class responsible for verifying proofs generated by the proving backend. It
    supports both Groth16 and UltraGroth proving systems. UltraGroth is
    currently disabled thus the `verify_ultra_groth` method raises a
    `NotImplementedError`.
    """

    def __init__(
        self,
        repos_dir,
        model_dir, 
        model_name, 
        engine: Engine,
        logger: Logger | None = None, 
        verbose: VerboseMode = VerboseMode.INFO, 
    ) -> None:
        """
        Initializes the Verifier instance with the model directory, model name,
        logger, verbosity level, and proving backend.
        
        Args:
            model_dir (str): The directory where the model is located.
            model_name (str): The name of the model.
            logger (Logger, optional): Logger instance for logging messages. Defaults to None.
            verbose (VerboseMode, optional): Verbosity level for logging. Defaults to VerboseMode.INFO.
            proving_backend (ProvingBackend, optional): The proving backend to use. Defaults to ProvingBackend.GROTH16.
        """
        
        self.repos_dir = repos_dir
        self.model_dir = model_dir
        self.model_name = model_name
        self.engine = engine

        self._verbose = verbose
        self.logger = logger
        if logger is None:
            self.logger = create_logger(self._verbose)
        
        match SYSTEM_NAME:
            case "x86_64-apple-darwin" | "x86_64-unknown-linux-gnu" :
                self.verifier_dir = 'build_prover'
            case "aarch64-apple-darwin":
                self.verifier_dir = 'build_prover_macos_arm64'
            case "aarch64-unknown-linux-gnu":
                self.verifier_dir = 'build_prover_arm64'


    def verify_groth(self, proof_dir: str) -> bool:
        """
        Verifies the proof using the Groth16 proving system.
        """
        
        if proof_dir is None:
            proof_dir = Path(self.model_dir) / f"{self.model_name}_circom"

        command = [
            f'{self.repos_dir}/ultragroth/{self.verifier_dir}/src/verifier',
            f'{self.model_dir}/{self.model_name}_circom/verification_key.json',
            f'{proof_dir}/{self.model_name}_public.json',
            f'{proof_dir}/{self.model_name}_proof.json'
        ]

        command_str = " ".join(command)
        console.print(f"[yellow]$ {command_str}[/]")
        
        try:
            subprocess.run(command, check=True, text=True, capture_output=True)
            self.logger.info("Your proof is valid")
            return True

        except subprocess.CalledProcessError as e:
            error_msg = e.stderr.strip()
            if len(error_msg) > 0:
                console.print(Panel.fit(error_msg, title="Error", border_style="red"))
            return False


    def verify_ultra_groth(self, proof_dir: str = None) -> bool:
        """
        Verifies the proof using the UltraGroth proving system.
        """
        
        circom_dir = Path(self.model_dir) / f"{self.model_name}_circom"
        if proof_dir is None:
            proof_dir = circom_dir
    
        command = [
            f"{self.repos_dir}/ultragroth/{self.verifier_dir}/src/verifier_ultra_groth",
            f"{circom_dir}/{self.model_name}_vkey.json",
            f"{proof_dir}/{self.model_name}_public.json",
            f"{proof_dir}/{self.model_name}_proof.json"
        ]

        command_str = " ".join(command)
        console.print(f"[yellow]$ {command_str}[/]")
        
        try:
            subprocess.run(command, check=True, text=True, capture_output=True)
            self.logger.info("Your proof is valid")
            return True
        
        except subprocess.CalledProcessError as e:
            error_msg = e.stderr.strip()
            if len(error_msg) > 0:
                console.print(Panel.fit(error_msg, title="Error", border_style="red"))
            
            raise

    def verify(self, proof_dir: str = None) -> bool:
        """
        Verifies the proof using the specified proving backend.
        Args:
            proof_dir (str, optional): The directory where the proof files are located. Defaults to None.
        """
        
        if isinstance(self.engine.proving_backend, Groth16):
            return self.verify_groth(proof_dir)
        elif isinstance(self.engine.proving_backend, UltraGroth):
            return self.verify_ultra_groth(proof_dir)
        else:
            raise NotImplementedError("This is unknown proving backend")
