// AUTOGENERATED
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include "header.h"


int main(int argc, char **argv)
{
    if (argc != 2) {
        perror("Invalid number of parameters, pass the <inputs.bin> file");
        return 1;
    }

    // Open the binary file for reading
    FILE *file = fopen(argv[1], "rb");
    if (!file) {
        perror("Failed to open <inputs.bin> file");
        return 1;
    }

    // Get file size
    fseek(file, 0, SEEK_END);
    long file_size = ftell(file);
    rewind(file);

    // Allocate buffer and read file content
    uint8_t *buffer = (uint8_t *)malloc(file_size);
    if (!buffer) {
        perror("Failed to allocate buffer");
        fclose(file);
        return 1;
    }
    fread(buffer, 1, file_size, file);
    fclose(file);

    // Call the model function
    {{ struct_name }} result = {{ function_name }}(buffer, file_size);

    // Save the result to output file
    FILE *output_file = fopen("{{ filename }}", "wb");
    if (!output_file) {
        perror("Failed to open {{ filename }}");
        free(buffer);
        return 1;
    }
    fwrite(result.data, 1, result.len, output_file);
    fclose(output_file);

    // Clean up
    free(buffer);
    free(result.data);

    printf("Processing complete! Output saved to groth16.wtns\n");
    return 0;
}